graph TD
    %% Acteurs
    Public((Utilisateur Public))
    Collector((Collector))
    Moderator((Moderator))
    Administrator((Administrator))

    %% Cas d'utilisation - Espace Public
    UC_Price[Consulter le Price Guide <br/> tendances/prix du marché]

    %% Cas d'utilisation - Espace Connecté (Collector)
    UC_Catalog[Consulter le catalogue global <br/> avec recherche/tri/pagination]
    UC_AddCol[Ajouter une pièce à sa <br/> collection personnelle]
    UC_Review[Laisser un avis sur un jeu]
    UC_Exchange[Proposer ou réaliser un <br/> échange direct]
    UC_Value[Calculer la valeur estimée <br/> de son inventaire]

    %% Cas d'utilisation - Modération
    UC_ModReview[Valider ou supprimer <br/> un avis]
    UC_HideGame[Masquer une fiche de jeu <br/> obsolète ou erronée]

    %% Cas d'utilisation - Admin
    UC_Admin[Gérer les rôles et <br/> les accès des membres]

    %% Liaisons Acteurs -> Cas d'utilisation
    Public --> UC_Price
    
    Collector --> UC_Catalog
    Collector --> UC_AddCol
    Collector --> UC_Review
    Collector --> UC_Exchange
    Collector --> UC_Value

    Moderator --> UC_ModReview
    Moderator --> UC_HideGame

    Administrator --> UC_Admin